### PR TITLE
add msteamsbridge image

### PR DESCRIPTION
**Pull request by fschade**

### CODE REVIEW

**Comment by micbar** [comment]
@fschade please wait for the final screenshot. @tbsbdr

**Comment by fschade** [comment]
@micbar, @tbsbdr here as an alternative.

msteamsbridge

**Comment by fschade** [comment]
@hurradieweltgehtunter , first short idea. Are you ok with it?

**Comment by hurradieweltgehtunter** [comment]
Thank you for your effort but if we're talking about the app image as used as for example on the marketplace there are guidelines and a process we need to follow.
I will push this and come back with an image.

**Review by hurradieweltgehtunter — CHANGES_REQUESTED** [review]
Not following the app image guidelines. I will come back with a proper image

**Comment by micbar** [comment]
@hurradieweltgehtunter thanks.

The app should be released this week.

**Comment by hurradieweltgehtunter** [comment]
> @hurradieweltgehtunter thanks.
> 
> The app should be released this week.

I'll do my best but the app image won't be ready that fast most certainly. App image is a relase blocker IMHO and known since a long time now.

**Comment by micbar** [comment]
we cannot delay this release, then we need a first image which can be enhanced later.

**Comment by hurradieweltgehtunter** [comment]
Lemme talk to the designer maybe they can do it quickly.

**Comment by hurradieweltgehtunter** [comment]
App image will come in the next 2 days.

**Comment by micbar** [comment]
@hurradieweltgehtunter status update? We could also merge this here and improve later.

**Review by hurradieweltgehtunter — APPROVED** [review]

**Comment by hurradieweltgehtunter** [comment]
Just uploaded the new image. Ready to go :)

**Pull request merged**
