### PR TITLE
New screenshot for Contacts 1.1

### PR DESCRIPTION
**Pull request by skjnldsv**

### CODE REVIEW

**Comment by Henni** [comment]
:+1:

**Comment by skjnldsv** [comment]
@Henni, what is the best way to proceed, should I wait for more reviews, or just merge now?

**Comment by Henni** [comment]
In general owncloud requires two thumbs up to merge a PR.
If in doubt wait for the maintainers of the repo to merge the PR (I believe in this case @jospoortvliet)

**Comment by skjnldsv** [comment]
Okay! :+1: :)

**Comment by MorrisJobke** [comment]
> In general owncloud requires two thumbs up to merge a PR.

This only applies for actual code and mostly also just for core and core apps.

**Comment by skjnldsv** [comment]
Thx Morris :)

**Comment by aspdye** [comment]
Can we add some profile pictures :confused: I know that it isn't possible to add them (via Web) but they are shown if you add them via CardDAV and I think that would make the screenshot nicer :grin:

cc @Henni @skjnldsv

**Comment by skjnldsv** [comment]
Well, currently we can't add picture, I don't thin this is a good idea to show a screenshot with some in it.
Maybe when the functionality will be implemented?

**Pull request merged**
