### PR TITLE
Update contacts for 9.0

### PR DESCRIPTION
**Pull request by Henni**

### CODE REVIEW

**Comment by aspdye** [comment]
Okay. I will already link this in the new README.md, but until this will be merged, we will show the old one :smile:

**Comment by jospoortvliet** [comment]
*awesome*

**Comment by jospoortvliet** [comment]
All we need now is Calendar... @georgehrke @tomneedham @DeepDiver1975  hint hint I'd like to feature the Calendar screenshot on owncloud.org/features but this Contacts one looks so cool I just might go for that ;-)

One last hint, @Henni - try to keep screenshots at a rather low resolution (small browser window) so that they still show detail when shown in thumb format. This is the main reason most screenshots here are 720P (1280x720), that is perfect when showing on a page like https://staging.owncloud.org/features ;-)

**Comment by georgehrke** [comment]
> All we need now is Calendar

On it

**Comment by georgehrke** [comment]
Can I just delete the old screenshots in calendar or are they in use somewhere?

**Comment by jospoortvliet** [comment]
just overwrite it

**Comment by georgehrke** [comment]
@jospoortvliet please review https://github.com/owncloud/screenshots/pull/10 ;)

**Pull request merged**
